// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadOHLC(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DownloadOHLC'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function FetchPairs(arg1) {
  return window['go']['main']['App']['FetchPairs'](arg1);
}
